// This file is generated by rust-protobuf 3.3.0. Do not edit
// .proto file is parsed by protoc 3.19.4
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `steammessages_star.steamclient.proto`

// @@protoc_insertion_point(message:CSTAR_KeyValueQuery)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct CSTAR_KeyValueQuery {
    // message fields
    // @@protoc_insertion_point(field:CSTAR_KeyValueQuery.key)
    pub key: ::std::option::Option<::std::string::String>,
    // @@protoc_insertion_point(field:CSTAR_KeyValueQuery.value)
    pub value: ::std::option::Option<::std::string::String>,
    // special fields
    // @@protoc_insertion_point(special_field:CSTAR_KeyValueQuery.special_fields)
    pub special_fields: crate::SpecialFields,
}

impl<'a> ::std::default::Default for &'a CSTAR_KeyValueQuery {
    fn default() -> &'a CSTAR_KeyValueQuery {
        <CSTAR_KeyValueQuery as crate::Message>::default_instance()
    }
}

impl CSTAR_KeyValueQuery {
    pub fn new() -> CSTAR_KeyValueQuery {
        ::std::default::Default::default()
    }

    // optional string key = 1;

    pub fn key(&self) -> &str {
        match self.key.as_ref() {
            Some(v) => v,
            None => "",
        }
    }

    pub fn clear_key(&mut self) {
        self.key = ::std::option::Option::None;
    }

    pub fn has_key(&self) -> bool {
        self.key.is_some()
    }

    // Param is passed by value, moved
    pub fn set_key(&mut self, v: ::std::string::String) {
        self.key = ::std::option::Option::Some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_key(&mut self) -> &mut ::std::string::String {
        if self.key.is_none() {
            self.key = ::std::option::Option::Some(::std::string::String::new());
        }
        self.key.as_mut().unwrap()
    }

    // Take field
    pub fn take_key(&mut self) -> ::std::string::String {
        self.key.take().unwrap_or_else(|| ::std::string::String::new())
    }

    // optional string value = 2;

    pub fn value(&self) -> &str {
        match self.value.as_ref() {
            Some(v) => v,
            None => "",
        }
    }

    pub fn clear_value(&mut self) {
        self.value = ::std::option::Option::None;
    }

    pub fn has_value(&self) -> bool {
        self.value.is_some()
    }

    // Param is passed by value, moved
    pub fn set_value(&mut self, v: ::std::string::String) {
        self.value = ::std::option::Option::Some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_value(&mut self) -> &mut ::std::string::String {
        if self.value.is_none() {
            self.value = ::std::option::Option::Some(::std::string::String::new());
        }
        self.value.as_mut().unwrap()
    }

    // Take field
    pub fn take_value(&mut self) -> ::std::string::String {
        self.value.take().unwrap_or_else(|| ::std::string::String::new())
    }

    fn generated_message_descriptor_data() -> crate::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(2);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(crate::reflect::rt::v2::make_option_accessor::<_, _>(
            "key",
            |m: &CSTAR_KeyValueQuery| { &m.key },
            |m: &mut CSTAR_KeyValueQuery| { &mut m.key },
        ));
        fields.push(crate::reflect::rt::v2::make_option_accessor::<_, _>(
            "value",
            |m: &CSTAR_KeyValueQuery| { &m.value },
            |m: &mut CSTAR_KeyValueQuery| { &mut m.value },
        ));
        crate::reflect::GeneratedMessageDescriptorData::new_2::<CSTAR_KeyValueQuery>(
            "CSTAR_KeyValueQuery",
            fields,
            oneofs,
        )
    }
}

impl crate::Message for CSTAR_KeyValueQuery {
    const NAME: &'static str = "CSTAR_KeyValueQuery";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut crate::CodedInputStream<'_>) -> crate::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.key = ::std::option::Option::Some(is.read_string()?);
                },
                18 => {
                    self.value = ::std::option::Option::Some(is.read_string()?);
                },
                tag => {
                    crate::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let Some(v) = self.key.as_ref() {
            my_size += crate::rt::string_size(1, &v);
        }
        if let Some(v) = self.value.as_ref() {
            my_size += crate::rt::string_size(2, &v);
        }
        my_size += crate::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut crate::CodedOutputStream<'_>) -> crate::Result<()> {
        if let Some(v) = self.key.as_ref() {
            os.write_string(1, v)?;
        }
        if let Some(v) = self.value.as_ref() {
            os.write_string(2, v)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &crate::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut crate::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> CSTAR_KeyValueQuery {
        CSTAR_KeyValueQuery::new()
    }

    fn clear(&mut self) {
        self.key = ::std::option::Option::None;
        self.value = ::std::option::Option::None;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static CSTAR_KeyValueQuery {
        static instance: CSTAR_KeyValueQuery = CSTAR_KeyValueQuery {
            key: ::std::option::Option::None,
            value: ::std::option::Option::None,
            special_fields: crate::SpecialFields::new(),
        };
        &instance
    }
}

impl crate::MessageFull for CSTAR_KeyValueQuery {
    fn descriptor() -> crate::reflect::MessageDescriptor {
        static descriptor: crate::rt::Lazy<crate::reflect::MessageDescriptor> = crate::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("CSTAR_KeyValueQuery").unwrap()).clone()
    }
}

impl ::std::fmt::Display for CSTAR_KeyValueQuery {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        crate::text_format::fmt(self, f)
    }
}

impl crate::reflect::ProtobufValue for CSTAR_KeyValueQuery {
    type RuntimeType = crate::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:CSTAR_GlyphQueryParams)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct CSTAR_GlyphQueryParams {
    // message fields
    // @@protoc_insertion_point(field:CSTAR_GlyphQueryParams.bundle_id)
    pub bundle_id: ::std::option::Option<u64>,
    // @@protoc_insertion_point(field:CSTAR_GlyphQueryParams.queries)
    pub queries: ::std::vec::Vec<CSTAR_KeyValueQuery>,
    // special fields
    // @@protoc_insertion_point(special_field:CSTAR_GlyphQueryParams.special_fields)
    pub special_fields: crate::SpecialFields,
}

impl<'a> ::std::default::Default for &'a CSTAR_GlyphQueryParams {
    fn default() -> &'a CSTAR_GlyphQueryParams {
        <CSTAR_GlyphQueryParams as crate::Message>::default_instance()
    }
}

impl CSTAR_GlyphQueryParams {
    pub fn new() -> CSTAR_GlyphQueryParams {
        ::std::default::Default::default()
    }

    // optional uint64 bundle_id = 1;

    pub fn bundle_id(&self) -> u64 {
        self.bundle_id.unwrap_or(0)
    }

    pub fn clear_bundle_id(&mut self) {
        self.bundle_id = ::std::option::Option::None;
    }

    pub fn has_bundle_id(&self) -> bool {
        self.bundle_id.is_some()
    }

    // Param is passed by value, moved
    pub fn set_bundle_id(&mut self, v: u64) {
        self.bundle_id = ::std::option::Option::Some(v);
    }

    // repeated .CSTAR_KeyValueQuery queries = 2;

    pub fn queries(&self) -> &[CSTAR_KeyValueQuery] {
        &self.queries
    }

    pub fn clear_queries(&mut self) {
        self.queries.clear();
    }

    // Param is passed by value, moved
    pub fn set_queries(&mut self, v: ::std::vec::Vec<CSTAR_KeyValueQuery>) {
        self.queries = v;
    }

    // Mutable pointer to the field.
    pub fn mut_queries(&mut self) -> &mut ::std::vec::Vec<CSTAR_KeyValueQuery> {
        &mut self.queries
    }

    // Take field
    pub fn take_queries(&mut self) -> ::std::vec::Vec<CSTAR_KeyValueQuery> {
        ::std::mem::replace(&mut self.queries, ::std::vec::Vec::new())
    }

    fn generated_message_descriptor_data() -> crate::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(2);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(crate::reflect::rt::v2::make_option_accessor::<_, _>(
            "bundle_id",
            |m: &CSTAR_GlyphQueryParams| { &m.bundle_id },
            |m: &mut CSTAR_GlyphQueryParams| { &mut m.bundle_id },
        ));
        fields.push(crate::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "queries",
            |m: &CSTAR_GlyphQueryParams| { &m.queries },
            |m: &mut CSTAR_GlyphQueryParams| { &mut m.queries },
        ));
        crate::reflect::GeneratedMessageDescriptorData::new_2::<CSTAR_GlyphQueryParams>(
            "CSTAR_GlyphQueryParams",
            fields,
            oneofs,
        )
    }
}

impl crate::Message for CSTAR_GlyphQueryParams {
    const NAME: &'static str = "CSTAR_GlyphQueryParams";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut crate::CodedInputStream<'_>) -> crate::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.bundle_id = ::std::option::Option::Some(is.read_uint64()?);
                },
                18 => {
                    self.queries.push(is.read_message()?);
                },
                tag => {
                    crate::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let Some(v) = self.bundle_id {
            my_size += crate::rt::uint64_size(1, v);
        }
        for value in &self.queries {
            let len = value.compute_size();
            my_size += 1 + crate::rt::compute_raw_varint64_size(len) + len;
        };
        my_size += crate::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut crate::CodedOutputStream<'_>) -> crate::Result<()> {
        if let Some(v) = self.bundle_id {
            os.write_uint64(1, v)?;
        }
        for v in &self.queries {
            crate::rt::write_message_field_with_cached_size(2, v, os)?;
        };
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &crate::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut crate::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> CSTAR_GlyphQueryParams {
        CSTAR_GlyphQueryParams::new()
    }

    fn clear(&mut self) {
        self.bundle_id = ::std::option::Option::None;
        self.queries.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static CSTAR_GlyphQueryParams {
        static instance: CSTAR_GlyphQueryParams = CSTAR_GlyphQueryParams {
            bundle_id: ::std::option::Option::None,
            queries: ::std::vec::Vec::new(),
            special_fields: crate::SpecialFields::new(),
        };
        &instance
    }
}

impl crate::MessageFull for CSTAR_GlyphQueryParams {
    fn descriptor() -> crate::reflect::MessageDescriptor {
        static descriptor: crate::rt::Lazy<crate::reflect::MessageDescriptor> = crate::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("CSTAR_GlyphQueryParams").unwrap()).clone()
    }
}

impl ::std::fmt::Display for CSTAR_GlyphQueryParams {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        crate::text_format::fmt(self, f)
    }
}

impl crate::reflect::ProtobufValue for CSTAR_GlyphQueryParams {
    type RuntimeType = crate::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:CSTAR_ReadGlyphData_Request)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct CSTAR_ReadGlyphData_Request {
    // message fields
    // @@protoc_insertion_point(field:CSTAR_ReadGlyphData_Request.query_params)
    pub query_params: crate::MessageField<CSTAR_GlyphQueryParams>,
    // @@protoc_insertion_point(field:CSTAR_ReadGlyphData_Request.last_modified_time_lower_limit)
    pub last_modified_time_lower_limit: ::std::option::Option<::std::string::String>,
    // special fields
    // @@protoc_insertion_point(special_field:CSTAR_ReadGlyphData_Request.special_fields)
    pub special_fields: crate::SpecialFields,
}

impl<'a> ::std::default::Default for &'a CSTAR_ReadGlyphData_Request {
    fn default() -> &'a CSTAR_ReadGlyphData_Request {
        <CSTAR_ReadGlyphData_Request as crate::Message>::default_instance()
    }
}

impl CSTAR_ReadGlyphData_Request {
    pub fn new() -> CSTAR_ReadGlyphData_Request {
        ::std::default::Default::default()
    }

    // optional .CSTAR_GlyphQueryParams query_params = 1;

    pub fn query_params(&self) -> &CSTAR_GlyphQueryParams {
        self.query_params.as_ref().unwrap_or_else(|| <CSTAR_GlyphQueryParams as crate::Message>::default_instance())
    }

    pub fn clear_query_params(&mut self) {
        self.query_params.clear();
    }

    pub fn has_query_params(&self) -> bool {
        self.query_params.is_some()
    }

    // Param is passed by value, moved
    pub fn set_query_params(&mut self, v: CSTAR_GlyphQueryParams) {
        self.query_params = crate::MessageField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_query_params(&mut self) -> &mut CSTAR_GlyphQueryParams {
        self.query_params.mut_or_insert_default()
    }

    // Take field
    pub fn take_query_params(&mut self) -> CSTAR_GlyphQueryParams {
        self.query_params.take().unwrap_or_else(|| CSTAR_GlyphQueryParams::new())
    }

    // optional string last_modified_time_lower_limit = 2;

    pub fn last_modified_time_lower_limit(&self) -> &str {
        match self.last_modified_time_lower_limit.as_ref() {
            Some(v) => v,
            None => "",
        }
    }

    pub fn clear_last_modified_time_lower_limit(&mut self) {
        self.last_modified_time_lower_limit = ::std::option::Option::None;
    }

    pub fn has_last_modified_time_lower_limit(&self) -> bool {
        self.last_modified_time_lower_limit.is_some()
    }

    // Param is passed by value, moved
    pub fn set_last_modified_time_lower_limit(&mut self, v: ::std::string::String) {
        self.last_modified_time_lower_limit = ::std::option::Option::Some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_last_modified_time_lower_limit(&mut self) -> &mut ::std::string::String {
        if self.last_modified_time_lower_limit.is_none() {
            self.last_modified_time_lower_limit = ::std::option::Option::Some(::std::string::String::new());
        }
        self.last_modified_time_lower_limit.as_mut().unwrap()
    }

    // Take field
    pub fn take_last_modified_time_lower_limit(&mut self) -> ::std::string::String {
        self.last_modified_time_lower_limit.take().unwrap_or_else(|| ::std::string::String::new())
    }

    fn generated_message_descriptor_data() -> crate::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(2);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(crate::reflect::rt::v2::make_message_field_accessor::<_, CSTAR_GlyphQueryParams>(
            "query_params",
            |m: &CSTAR_ReadGlyphData_Request| { &m.query_params },
            |m: &mut CSTAR_ReadGlyphData_Request| { &mut m.query_params },
        ));
        fields.push(crate::reflect::rt::v2::make_option_accessor::<_, _>(
            "last_modified_time_lower_limit",
            |m: &CSTAR_ReadGlyphData_Request| { &m.last_modified_time_lower_limit },
            |m: &mut CSTAR_ReadGlyphData_Request| { &mut m.last_modified_time_lower_limit },
        ));
        crate::reflect::GeneratedMessageDescriptorData::new_2::<CSTAR_ReadGlyphData_Request>(
            "CSTAR_ReadGlyphData_Request",
            fields,
            oneofs,
        )
    }
}

impl crate::Message for CSTAR_ReadGlyphData_Request {
    const NAME: &'static str = "CSTAR_ReadGlyphData_Request";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut crate::CodedInputStream<'_>) -> crate::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    crate::rt::read_singular_message_into_field(is, &mut self.query_params)?;
                },
                18 => {
                    self.last_modified_time_lower_limit = ::std::option::Option::Some(is.read_string()?);
                },
                tag => {
                    crate::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let Some(v) = self.query_params.as_ref() {
            let len = v.compute_size();
            my_size += 1 + crate::rt::compute_raw_varint64_size(len) + len;
        }
        if let Some(v) = self.last_modified_time_lower_limit.as_ref() {
            my_size += crate::rt::string_size(2, &v);
        }
        my_size += crate::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut crate::CodedOutputStream<'_>) -> crate::Result<()> {
        if let Some(v) = self.query_params.as_ref() {
            crate::rt::write_message_field_with_cached_size(1, v, os)?;
        }
        if let Some(v) = self.last_modified_time_lower_limit.as_ref() {
            os.write_string(2, v)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &crate::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut crate::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> CSTAR_ReadGlyphData_Request {
        CSTAR_ReadGlyphData_Request::new()
    }

    fn clear(&mut self) {
        self.query_params.clear();
        self.last_modified_time_lower_limit = ::std::option::Option::None;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static CSTAR_ReadGlyphData_Request {
        static instance: CSTAR_ReadGlyphData_Request = CSTAR_ReadGlyphData_Request {
            query_params: crate::MessageField::none(),
            last_modified_time_lower_limit: ::std::option::Option::None,
            special_fields: crate::SpecialFields::new(),
        };
        &instance
    }
}

impl crate::MessageFull for CSTAR_ReadGlyphData_Request {
    fn descriptor() -> crate::reflect::MessageDescriptor {
        static descriptor: crate::rt::Lazy<crate::reflect::MessageDescriptor> = crate::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("CSTAR_ReadGlyphData_Request").unwrap()).clone()
    }
}

impl ::std::fmt::Display for CSTAR_ReadGlyphData_Request {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        crate::text_format::fmt(self, f)
    }
}

impl crate::reflect::ProtobufValue for CSTAR_ReadGlyphData_Request {
    type RuntimeType = crate::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:CSTAR_GlyphData)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct CSTAR_GlyphData {
    // message fields
    // @@protoc_insertion_point(field:CSTAR_GlyphData.glyph_guid)
    pub glyph_guid: ::std::option::Option<::bytes::Bytes>,
    // @@protoc_insertion_point(field:CSTAR_GlyphData.glyph_last_modified)
    pub glyph_last_modified: ::std::option::Option<::std::string::String>,
    // @@protoc_insertion_point(field:CSTAR_GlyphData.glyph_json_data)
    pub glyph_json_data: ::std::option::Option<::std::string::String>,
    // special fields
    // @@protoc_insertion_point(special_field:CSTAR_GlyphData.special_fields)
    pub special_fields: crate::SpecialFields,
}

impl<'a> ::std::default::Default for &'a CSTAR_GlyphData {
    fn default() -> &'a CSTAR_GlyphData {
        <CSTAR_GlyphData as crate::Message>::default_instance()
    }
}

impl CSTAR_GlyphData {
    pub fn new() -> CSTAR_GlyphData {
        ::std::default::Default::default()
    }

    // optional bytes glyph_guid = 1;

    pub fn glyph_guid(&self) -> &[u8] {
        match self.glyph_guid.as_ref() {
            Some(v) => v,
            None => &[],
        }
    }

    pub fn clear_glyph_guid(&mut self) {
        self.glyph_guid = ::std::option::Option::None;
    }

    pub fn has_glyph_guid(&self) -> bool {
        self.glyph_guid.is_some()
    }

    // Param is passed by value, moved
    pub fn set_glyph_guid(&mut self, v: ::bytes::Bytes) {
        self.glyph_guid = ::std::option::Option::Some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_glyph_guid(&mut self) -> &mut ::bytes::Bytes {
        if self.glyph_guid.is_none() {
            self.glyph_guid = ::std::option::Option::Some(::bytes::Bytes::new());
        }
        self.glyph_guid.as_mut().unwrap()
    }

    // Take field
    pub fn take_glyph_guid(&mut self) -> ::bytes::Bytes {
        self.glyph_guid.take().unwrap_or_else(|| ::bytes::Bytes::new())
    }

    // optional string glyph_last_modified = 2;

    pub fn glyph_last_modified(&self) -> &str {
        match self.glyph_last_modified.as_ref() {
            Some(v) => v,
            None => "",
        }
    }

    pub fn clear_glyph_last_modified(&mut self) {
        self.glyph_last_modified = ::std::option::Option::None;
    }

    pub fn has_glyph_last_modified(&self) -> bool {
        self.glyph_last_modified.is_some()
    }

    // Param is passed by value, moved
    pub fn set_glyph_last_modified(&mut self, v: ::std::string::String) {
        self.glyph_last_modified = ::std::option::Option::Some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_glyph_last_modified(&mut self) -> &mut ::std::string::String {
        if self.glyph_last_modified.is_none() {
            self.glyph_last_modified = ::std::option::Option::Some(::std::string::String::new());
        }
        self.glyph_last_modified.as_mut().unwrap()
    }

    // Take field
    pub fn take_glyph_last_modified(&mut self) -> ::std::string::String {
        self.glyph_last_modified.take().unwrap_or_else(|| ::std::string::String::new())
    }

    // optional string glyph_json_data = 3;

    pub fn glyph_json_data(&self) -> &str {
        match self.glyph_json_data.as_ref() {
            Some(v) => v,
            None => "",
        }
    }

    pub fn clear_glyph_json_data(&mut self) {
        self.glyph_json_data = ::std::option::Option::None;
    }

    pub fn has_glyph_json_data(&self) -> bool {
        self.glyph_json_data.is_some()
    }

    // Param is passed by value, moved
    pub fn set_glyph_json_data(&mut self, v: ::std::string::String) {
        self.glyph_json_data = ::std::option::Option::Some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_glyph_json_data(&mut self) -> &mut ::std::string::String {
        if self.glyph_json_data.is_none() {
            self.glyph_json_data = ::std::option::Option::Some(::std::string::String::new());
        }
        self.glyph_json_data.as_mut().unwrap()
    }

    // Take field
    pub fn take_glyph_json_data(&mut self) -> ::std::string::String {
        self.glyph_json_data.take().unwrap_or_else(|| ::std::string::String::new())
    }

    fn generated_message_descriptor_data() -> crate::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(3);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(crate::reflect::rt::v2::make_option_accessor::<_, _>(
            "glyph_guid",
            |m: &CSTAR_GlyphData| { &m.glyph_guid },
            |m: &mut CSTAR_GlyphData| { &mut m.glyph_guid },
        ));
        fields.push(crate::reflect::rt::v2::make_option_accessor::<_, _>(
            "glyph_last_modified",
            |m: &CSTAR_GlyphData| { &m.glyph_last_modified },
            |m: &mut CSTAR_GlyphData| { &mut m.glyph_last_modified },
        ));
        fields.push(crate::reflect::rt::v2::make_option_accessor::<_, _>(
            "glyph_json_data",
            |m: &CSTAR_GlyphData| { &m.glyph_json_data },
            |m: &mut CSTAR_GlyphData| { &mut m.glyph_json_data },
        ));
        crate::reflect::GeneratedMessageDescriptorData::new_2::<CSTAR_GlyphData>(
            "CSTAR_GlyphData",
            fields,
            oneofs,
        )
    }
}

impl crate::Message for CSTAR_GlyphData {
    const NAME: &'static str = "CSTAR_GlyphData";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut crate::CodedInputStream<'_>) -> crate::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.glyph_guid = ::std::option::Option::Some(is.read_tokio_bytes()?);
                },
                18 => {
                    self.glyph_last_modified = ::std::option::Option::Some(is.read_string()?);
                },
                26 => {
                    self.glyph_json_data = ::std::option::Option::Some(is.read_string()?);
                },
                tag => {
                    crate::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let Some(v) = self.glyph_guid.as_ref() {
            my_size += crate::rt::bytes_size(1, &v);
        }
        if let Some(v) = self.glyph_last_modified.as_ref() {
            my_size += crate::rt::string_size(2, &v);
        }
        if let Some(v) = self.glyph_json_data.as_ref() {
            my_size += crate::rt::string_size(3, &v);
        }
        my_size += crate::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut crate::CodedOutputStream<'_>) -> crate::Result<()> {
        if let Some(v) = self.glyph_guid.as_ref() {
            os.write_bytes(1, v)?;
        }
        if let Some(v) = self.glyph_last_modified.as_ref() {
            os.write_string(2, v)?;
        }
        if let Some(v) = self.glyph_json_data.as_ref() {
            os.write_string(3, v)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &crate::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut crate::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> CSTAR_GlyphData {
        CSTAR_GlyphData::new()
    }

    fn clear(&mut self) {
        self.glyph_guid = ::std::option::Option::None;
        self.glyph_last_modified = ::std::option::Option::None;
        self.glyph_json_data = ::std::option::Option::None;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static CSTAR_GlyphData {
        static instance: CSTAR_GlyphData = CSTAR_GlyphData {
            glyph_guid: ::std::option::Option::None,
            glyph_last_modified: ::std::option::Option::None,
            glyph_json_data: ::std::option::Option::None,
            special_fields: crate::SpecialFields::new(),
        };
        &instance
    }
}

impl crate::MessageFull for CSTAR_GlyphData {
    fn descriptor() -> crate::reflect::MessageDescriptor {
        static descriptor: crate::rt::Lazy<crate::reflect::MessageDescriptor> = crate::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("CSTAR_GlyphData").unwrap()).clone()
    }
}

impl ::std::fmt::Display for CSTAR_GlyphData {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        crate::text_format::fmt(self, f)
    }
}

impl crate::reflect::ProtobufValue for CSTAR_GlyphData {
    type RuntimeType = crate::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:CSTAR_WriteGlyphData_Request)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct CSTAR_WriteGlyphData_Request {
    // message fields
    // @@protoc_insertion_point(field:CSTAR_WriteGlyphData_Request.bundle_id)
    pub bundle_id: ::std::option::Option<u64>,
    // @@protoc_insertion_point(field:CSTAR_WriteGlyphData_Request.glyph_data)
    pub glyph_data: ::std::vec::Vec<CSTAR_GlyphData>,
    // special fields
    // @@protoc_insertion_point(special_field:CSTAR_WriteGlyphData_Request.special_fields)
    pub special_fields: crate::SpecialFields,
}

impl<'a> ::std::default::Default for &'a CSTAR_WriteGlyphData_Request {
    fn default() -> &'a CSTAR_WriteGlyphData_Request {
        <CSTAR_WriteGlyphData_Request as crate::Message>::default_instance()
    }
}

impl CSTAR_WriteGlyphData_Request {
    pub fn new() -> CSTAR_WriteGlyphData_Request {
        ::std::default::Default::default()
    }

    // optional uint64 bundle_id = 1;

    pub fn bundle_id(&self) -> u64 {
        self.bundle_id.unwrap_or(0)
    }

    pub fn clear_bundle_id(&mut self) {
        self.bundle_id = ::std::option::Option::None;
    }

    pub fn has_bundle_id(&self) -> bool {
        self.bundle_id.is_some()
    }

    // Param is passed by value, moved
    pub fn set_bundle_id(&mut self, v: u64) {
        self.bundle_id = ::std::option::Option::Some(v);
    }

    // repeated .CSTAR_GlyphData glyph_data = 2;

    pub fn glyph_data(&self) -> &[CSTAR_GlyphData] {
        &self.glyph_data
    }

    pub fn clear_glyph_data(&mut self) {
        self.glyph_data.clear();
    }

    // Param is passed by value, moved
    pub fn set_glyph_data(&mut self, v: ::std::vec::Vec<CSTAR_GlyphData>) {
        self.glyph_data = v;
    }

    // Mutable pointer to the field.
    pub fn mut_glyph_data(&mut self) -> &mut ::std::vec::Vec<CSTAR_GlyphData> {
        &mut self.glyph_data
    }

    // Take field
    pub fn take_glyph_data(&mut self) -> ::std::vec::Vec<CSTAR_GlyphData> {
        ::std::mem::replace(&mut self.glyph_data, ::std::vec::Vec::new())
    }

    fn generated_message_descriptor_data() -> crate::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(2);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(crate::reflect::rt::v2::make_option_accessor::<_, _>(
            "bundle_id",
            |m: &CSTAR_WriteGlyphData_Request| { &m.bundle_id },
            |m: &mut CSTAR_WriteGlyphData_Request| { &mut m.bundle_id },
        ));
        fields.push(crate::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "glyph_data",
            |m: &CSTAR_WriteGlyphData_Request| { &m.glyph_data },
            |m: &mut CSTAR_WriteGlyphData_Request| { &mut m.glyph_data },
        ));
        crate::reflect::GeneratedMessageDescriptorData::new_2::<CSTAR_WriteGlyphData_Request>(
            "CSTAR_WriteGlyphData_Request",
            fields,
            oneofs,
        )
    }
}

impl crate::Message for CSTAR_WriteGlyphData_Request {
    const NAME: &'static str = "CSTAR_WriteGlyphData_Request";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut crate::CodedInputStream<'_>) -> crate::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.bundle_id = ::std::option::Option::Some(is.read_uint64()?);
                },
                18 => {
                    self.glyph_data.push(is.read_message()?);
                },
                tag => {
                    crate::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let Some(v) = self.bundle_id {
            my_size += crate::rt::uint64_size(1, v);
        }
        for value in &self.glyph_data {
            let len = value.compute_size();
            my_size += 1 + crate::rt::compute_raw_varint64_size(len) + len;
        };
        my_size += crate::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut crate::CodedOutputStream<'_>) -> crate::Result<()> {
        if let Some(v) = self.bundle_id {
            os.write_uint64(1, v)?;
        }
        for v in &self.glyph_data {
            crate::rt::write_message_field_with_cached_size(2, v, os)?;
        };
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &crate::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut crate::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> CSTAR_WriteGlyphData_Request {
        CSTAR_WriteGlyphData_Request::new()
    }

    fn clear(&mut self) {
        self.bundle_id = ::std::option::Option::None;
        self.glyph_data.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static CSTAR_WriteGlyphData_Request {
        static instance: CSTAR_WriteGlyphData_Request = CSTAR_WriteGlyphData_Request {
            bundle_id: ::std::option::Option::None,
            glyph_data: ::std::vec::Vec::new(),
            special_fields: crate::SpecialFields::new(),
        };
        &instance
    }
}

impl crate::MessageFull for CSTAR_WriteGlyphData_Request {
    fn descriptor() -> crate::reflect::MessageDescriptor {
        static descriptor: crate::rt::Lazy<crate::reflect::MessageDescriptor> = crate::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("CSTAR_WriteGlyphData_Request").unwrap()).clone()
    }
}

impl ::std::fmt::Display for CSTAR_WriteGlyphData_Request {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        crate::text_format::fmt(self, f)
    }
}

impl crate::reflect::ProtobufValue for CSTAR_WriteGlyphData_Request {
    type RuntimeType = crate::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:CSTAR_Request)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct CSTAR_Request {
    // message fields
    // @@protoc_insertion_point(field:CSTAR_Request.read_glyph_data)
    pub read_glyph_data: crate::MessageField<CSTAR_ReadGlyphData_Request>,
    // @@protoc_insertion_point(field:CSTAR_Request.write_glyph_data)
    pub write_glyph_data: crate::MessageField<CSTAR_WriteGlyphData_Request>,
    // special fields
    // @@protoc_insertion_point(special_field:CSTAR_Request.special_fields)
    pub special_fields: crate::SpecialFields,
}

impl<'a> ::std::default::Default for &'a CSTAR_Request {
    fn default() -> &'a CSTAR_Request {
        <CSTAR_Request as crate::Message>::default_instance()
    }
}

impl CSTAR_Request {
    pub fn new() -> CSTAR_Request {
        ::std::default::Default::default()
    }

    // optional .CSTAR_ReadGlyphData_Request read_glyph_data = 1;

    pub fn read_glyph_data(&self) -> &CSTAR_ReadGlyphData_Request {
        self.read_glyph_data.as_ref().unwrap_or_else(|| <CSTAR_ReadGlyphData_Request as crate::Message>::default_instance())
    }

    pub fn clear_read_glyph_data(&mut self) {
        self.read_glyph_data.clear();
    }

    pub fn has_read_glyph_data(&self) -> bool {
        self.read_glyph_data.is_some()
    }

    // Param is passed by value, moved
    pub fn set_read_glyph_data(&mut self, v: CSTAR_ReadGlyphData_Request) {
        self.read_glyph_data = crate::MessageField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_read_glyph_data(&mut self) -> &mut CSTAR_ReadGlyphData_Request {
        self.read_glyph_data.mut_or_insert_default()
    }

    // Take field
    pub fn take_read_glyph_data(&mut self) -> CSTAR_ReadGlyphData_Request {
        self.read_glyph_data.take().unwrap_or_else(|| CSTAR_ReadGlyphData_Request::new())
    }

    // optional .CSTAR_WriteGlyphData_Request write_glyph_data = 2;

    pub fn write_glyph_data(&self) -> &CSTAR_WriteGlyphData_Request {
        self.write_glyph_data.as_ref().unwrap_or_else(|| <CSTAR_WriteGlyphData_Request as crate::Message>::default_instance())
    }

    pub fn clear_write_glyph_data(&mut self) {
        self.write_glyph_data.clear();
    }

    pub fn has_write_glyph_data(&self) -> bool {
        self.write_glyph_data.is_some()
    }

    // Param is passed by value, moved
    pub fn set_write_glyph_data(&mut self, v: CSTAR_WriteGlyphData_Request) {
        self.write_glyph_data = crate::MessageField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_write_glyph_data(&mut self) -> &mut CSTAR_WriteGlyphData_Request {
        self.write_glyph_data.mut_or_insert_default()
    }

    // Take field
    pub fn take_write_glyph_data(&mut self) -> CSTAR_WriteGlyphData_Request {
        self.write_glyph_data.take().unwrap_or_else(|| CSTAR_WriteGlyphData_Request::new())
    }

    fn generated_message_descriptor_data() -> crate::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(2);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(crate::reflect::rt::v2::make_message_field_accessor::<_, CSTAR_ReadGlyphData_Request>(
            "read_glyph_data",
            |m: &CSTAR_Request| { &m.read_glyph_data },
            |m: &mut CSTAR_Request| { &mut m.read_glyph_data },
        ));
        fields.push(crate::reflect::rt::v2::make_message_field_accessor::<_, CSTAR_WriteGlyphData_Request>(
            "write_glyph_data",
            |m: &CSTAR_Request| { &m.write_glyph_data },
            |m: &mut CSTAR_Request| { &mut m.write_glyph_data },
        ));
        crate::reflect::GeneratedMessageDescriptorData::new_2::<CSTAR_Request>(
            "CSTAR_Request",
            fields,
            oneofs,
        )
    }
}

impl crate::Message for CSTAR_Request {
    const NAME: &'static str = "CSTAR_Request";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut crate::CodedInputStream<'_>) -> crate::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    crate::rt::read_singular_message_into_field(is, &mut self.read_glyph_data)?;
                },
                18 => {
                    crate::rt::read_singular_message_into_field(is, &mut self.write_glyph_data)?;
                },
                tag => {
                    crate::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let Some(v) = self.read_glyph_data.as_ref() {
            let len = v.compute_size();
            my_size += 1 + crate::rt::compute_raw_varint64_size(len) + len;
        }
        if let Some(v) = self.write_glyph_data.as_ref() {
            let len = v.compute_size();
            my_size += 1 + crate::rt::compute_raw_varint64_size(len) + len;
        }
        my_size += crate::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut crate::CodedOutputStream<'_>) -> crate::Result<()> {
        if let Some(v) = self.read_glyph_data.as_ref() {
            crate::rt::write_message_field_with_cached_size(1, v, os)?;
        }
        if let Some(v) = self.write_glyph_data.as_ref() {
            crate::rt::write_message_field_with_cached_size(2, v, os)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &crate::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut crate::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> CSTAR_Request {
        CSTAR_Request::new()
    }

    fn clear(&mut self) {
        self.read_glyph_data.clear();
        self.write_glyph_data.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static CSTAR_Request {
        static instance: CSTAR_Request = CSTAR_Request {
            read_glyph_data: crate::MessageField::none(),
            write_glyph_data: crate::MessageField::none(),
            special_fields: crate::SpecialFields::new(),
        };
        &instance
    }
}

impl crate::MessageFull for CSTAR_Request {
    fn descriptor() -> crate::reflect::MessageDescriptor {
        static descriptor: crate::rt::Lazy<crate::reflect::MessageDescriptor> = crate::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("CSTAR_Request").unwrap()).clone()
    }
}

impl ::std::fmt::Display for CSTAR_Request {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        crate::text_format::fmt(self, f)
    }
}

impl crate::reflect::ProtobufValue for CSTAR_Request {
    type RuntimeType = crate::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:CSTAR_ReadGlyphData_Response)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct CSTAR_ReadGlyphData_Response {
    // message fields
    // @@protoc_insertion_point(field:CSTAR_ReadGlyphData_Response.bundle_id)
    pub bundle_id: ::std::option::Option<u64>,
    // @@protoc_insertion_point(field:CSTAR_ReadGlyphData_Response.glyph_data)
    pub glyph_data: ::std::vec::Vec<CSTAR_GlyphData>,
    // special fields
    // @@protoc_insertion_point(special_field:CSTAR_ReadGlyphData_Response.special_fields)
    pub special_fields: crate::SpecialFields,
}

impl<'a> ::std::default::Default for &'a CSTAR_ReadGlyphData_Response {
    fn default() -> &'a CSTAR_ReadGlyphData_Response {
        <CSTAR_ReadGlyphData_Response as crate::Message>::default_instance()
    }
}

impl CSTAR_ReadGlyphData_Response {
    pub fn new() -> CSTAR_ReadGlyphData_Response {
        ::std::default::Default::default()
    }

    // optional uint64 bundle_id = 1;

    pub fn bundle_id(&self) -> u64 {
        self.bundle_id.unwrap_or(0)
    }

    pub fn clear_bundle_id(&mut self) {
        self.bundle_id = ::std::option::Option::None;
    }

    pub fn has_bundle_id(&self) -> bool {
        self.bundle_id.is_some()
    }

    // Param is passed by value, moved
    pub fn set_bundle_id(&mut self, v: u64) {
        self.bundle_id = ::std::option::Option::Some(v);
    }

    // repeated .CSTAR_GlyphData glyph_data = 2;

    pub fn glyph_data(&self) -> &[CSTAR_GlyphData] {
        &self.glyph_data
    }

    pub fn clear_glyph_data(&mut self) {
        self.glyph_data.clear();
    }

    // Param is passed by value, moved
    pub fn set_glyph_data(&mut self, v: ::std::vec::Vec<CSTAR_GlyphData>) {
        self.glyph_data = v;
    }

    // Mutable pointer to the field.
    pub fn mut_glyph_data(&mut self) -> &mut ::std::vec::Vec<CSTAR_GlyphData> {
        &mut self.glyph_data
    }

    // Take field
    pub fn take_glyph_data(&mut self) -> ::std::vec::Vec<CSTAR_GlyphData> {
        ::std::mem::replace(&mut self.glyph_data, ::std::vec::Vec::new())
    }

    fn generated_message_descriptor_data() -> crate::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(2);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(crate::reflect::rt::v2::make_option_accessor::<_, _>(
            "bundle_id",
            |m: &CSTAR_ReadGlyphData_Response| { &m.bundle_id },
            |m: &mut CSTAR_ReadGlyphData_Response| { &mut m.bundle_id },
        ));
        fields.push(crate::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "glyph_data",
            |m: &CSTAR_ReadGlyphData_Response| { &m.glyph_data },
            |m: &mut CSTAR_ReadGlyphData_Response| { &mut m.glyph_data },
        ));
        crate::reflect::GeneratedMessageDescriptorData::new_2::<CSTAR_ReadGlyphData_Response>(
            "CSTAR_ReadGlyphData_Response",
            fields,
            oneofs,
        )
    }
}

impl crate::Message for CSTAR_ReadGlyphData_Response {
    const NAME: &'static str = "CSTAR_ReadGlyphData_Response";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut crate::CodedInputStream<'_>) -> crate::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.bundle_id = ::std::option::Option::Some(is.read_uint64()?);
                },
                18 => {
                    self.glyph_data.push(is.read_message()?);
                },
                tag => {
                    crate::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let Some(v) = self.bundle_id {
            my_size += crate::rt::uint64_size(1, v);
        }
        for value in &self.glyph_data {
            let len = value.compute_size();
            my_size += 1 + crate::rt::compute_raw_varint64_size(len) + len;
        };
        my_size += crate::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut crate::CodedOutputStream<'_>) -> crate::Result<()> {
        if let Some(v) = self.bundle_id {
            os.write_uint64(1, v)?;
        }
        for v in &self.glyph_data {
            crate::rt::write_message_field_with_cached_size(2, v, os)?;
        };
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &crate::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut crate::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> CSTAR_ReadGlyphData_Response {
        CSTAR_ReadGlyphData_Response::new()
    }

    fn clear(&mut self) {
        self.bundle_id = ::std::option::Option::None;
        self.glyph_data.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static CSTAR_ReadGlyphData_Response {
        static instance: CSTAR_ReadGlyphData_Response = CSTAR_ReadGlyphData_Response {
            bundle_id: ::std::option::Option::None,
            glyph_data: ::std::vec::Vec::new(),
            special_fields: crate::SpecialFields::new(),
        };
        &instance
    }
}

impl crate::MessageFull for CSTAR_ReadGlyphData_Response {
    fn descriptor() -> crate::reflect::MessageDescriptor {
        static descriptor: crate::rt::Lazy<crate::reflect::MessageDescriptor> = crate::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("CSTAR_ReadGlyphData_Response").unwrap()).clone()
    }
}

impl ::std::fmt::Display for CSTAR_ReadGlyphData_Response {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        crate::text_format::fmt(self, f)
    }
}

impl crate::reflect::ProtobufValue for CSTAR_ReadGlyphData_Response {
    type RuntimeType = crate::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:CSTAR_WriteGlyphData_Response)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct CSTAR_WriteGlyphData_Response {
    // message fields
    // @@protoc_insertion_point(field:CSTAR_WriteGlyphData_Response.result)
    pub result: ::std::vec::Vec<crate::EnumOrUnknown<E_STAR_GlyphWriteResult>>,
    // special fields
    // @@protoc_insertion_point(special_field:CSTAR_WriteGlyphData_Response.special_fields)
    pub special_fields: crate::SpecialFields,
}

impl<'a> ::std::default::Default for &'a CSTAR_WriteGlyphData_Response {
    fn default() -> &'a CSTAR_WriteGlyphData_Response {
        <CSTAR_WriteGlyphData_Response as crate::Message>::default_instance()
    }
}

impl CSTAR_WriteGlyphData_Response {
    pub fn new() -> CSTAR_WriteGlyphData_Response {
        ::std::default::Default::default()
    }

    // repeated .E_STAR_GlyphWriteResult result = 1;

    pub fn result(&self) -> &[crate::EnumOrUnknown<E_STAR_GlyphWriteResult>] {
        &self.result
    }

    pub fn clear_result(&mut self) {
        self.result.clear();
    }

    // Param is passed by value, moved
    pub fn set_result(&mut self, v: ::std::vec::Vec<crate::EnumOrUnknown<E_STAR_GlyphWriteResult>>) {
        self.result = v;
    }

    // Mutable pointer to the field.
    pub fn mut_result(&mut self) -> &mut ::std::vec::Vec<crate::EnumOrUnknown<E_STAR_GlyphWriteResult>> {
        &mut self.result
    }

    // Take field
    pub fn take_result(&mut self) -> ::std::vec::Vec<crate::EnumOrUnknown<E_STAR_GlyphWriteResult>> {
        ::std::mem::replace(&mut self.result, ::std::vec::Vec::new())
    }

    fn generated_message_descriptor_data() -> crate::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(1);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(crate::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "result",
            |m: &CSTAR_WriteGlyphData_Response| { &m.result },
            |m: &mut CSTAR_WriteGlyphData_Response| { &mut m.result },
        ));
        crate::reflect::GeneratedMessageDescriptorData::new_2::<CSTAR_WriteGlyphData_Response>(
            "CSTAR_WriteGlyphData_Response",
            fields,
            oneofs,
        )
    }
}

impl crate::Message for CSTAR_WriteGlyphData_Response {
    const NAME: &'static str = "CSTAR_WriteGlyphData_Response";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut crate::CodedInputStream<'_>) -> crate::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.result.push(is.read_enum_or_unknown()?);
                },
                10 => {
                    crate::rt::read_repeated_packed_enum_or_unknown_into(is, &mut self.result)?
                },
                tag => {
                    crate::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        for value in &self.result {
            my_size += crate::rt::int32_size(1, value.value());
        };
        my_size += crate::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut crate::CodedOutputStream<'_>) -> crate::Result<()> {
        for v in &self.result {
            os.write_enum(1, crate::EnumOrUnknown::value(v))?;
        };
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &crate::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut crate::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> CSTAR_WriteGlyphData_Response {
        CSTAR_WriteGlyphData_Response::new()
    }

    fn clear(&mut self) {
        self.result.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static CSTAR_WriteGlyphData_Response {
        static instance: CSTAR_WriteGlyphData_Response = CSTAR_WriteGlyphData_Response {
            result: ::std::vec::Vec::new(),
            special_fields: crate::SpecialFields::new(),
        };
        &instance
    }
}

impl crate::MessageFull for CSTAR_WriteGlyphData_Response {
    fn descriptor() -> crate::reflect::MessageDescriptor {
        static descriptor: crate::rt::Lazy<crate::reflect::MessageDescriptor> = crate::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("CSTAR_WriteGlyphData_Response").unwrap()).clone()
    }
}

impl ::std::fmt::Display for CSTAR_WriteGlyphData_Response {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        crate::text_format::fmt(self, f)
    }
}

impl crate::reflect::ProtobufValue for CSTAR_WriteGlyphData_Response {
    type RuntimeType = crate::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:CSTAR_Response)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct CSTAR_Response {
    // message fields
    // @@protoc_insertion_point(field:CSTAR_Response.read_glyph_data)
    pub read_glyph_data: crate::MessageField<CSTAR_ReadGlyphData_Response>,
    // @@protoc_insertion_point(field:CSTAR_Response.write_glyph_data)
    pub write_glyph_data: crate::MessageField<CSTAR_WriteGlyphData_Response>,
    // special fields
    // @@protoc_insertion_point(special_field:CSTAR_Response.special_fields)
    pub special_fields: crate::SpecialFields,
}

impl<'a> ::std::default::Default for &'a CSTAR_Response {
    fn default() -> &'a CSTAR_Response {
        <CSTAR_Response as crate::Message>::default_instance()
    }
}

impl CSTAR_Response {
    pub fn new() -> CSTAR_Response {
        ::std::default::Default::default()
    }

    // optional .CSTAR_ReadGlyphData_Response read_glyph_data = 1;

    pub fn read_glyph_data(&self) -> &CSTAR_ReadGlyphData_Response {
        self.read_glyph_data.as_ref().unwrap_or_else(|| <CSTAR_ReadGlyphData_Response as crate::Message>::default_instance())
    }

    pub fn clear_read_glyph_data(&mut self) {
        self.read_glyph_data.clear();
    }

    pub fn has_read_glyph_data(&self) -> bool {
        self.read_glyph_data.is_some()
    }

    // Param is passed by value, moved
    pub fn set_read_glyph_data(&mut self, v: CSTAR_ReadGlyphData_Response) {
        self.read_glyph_data = crate::MessageField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_read_glyph_data(&mut self) -> &mut CSTAR_ReadGlyphData_Response {
        self.read_glyph_data.mut_or_insert_default()
    }

    // Take field
    pub fn take_read_glyph_data(&mut self) -> CSTAR_ReadGlyphData_Response {
        self.read_glyph_data.take().unwrap_or_else(|| CSTAR_ReadGlyphData_Response::new())
    }

    // optional .CSTAR_WriteGlyphData_Response write_glyph_data = 2;

    pub fn write_glyph_data(&self) -> &CSTAR_WriteGlyphData_Response {
        self.write_glyph_data.as_ref().unwrap_or_else(|| <CSTAR_WriteGlyphData_Response as crate::Message>::default_instance())
    }

    pub fn clear_write_glyph_data(&mut self) {
        self.write_glyph_data.clear();
    }

    pub fn has_write_glyph_data(&self) -> bool {
        self.write_glyph_data.is_some()
    }

    // Param is passed by value, moved
    pub fn set_write_glyph_data(&mut self, v: CSTAR_WriteGlyphData_Response) {
        self.write_glyph_data = crate::MessageField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_write_glyph_data(&mut self) -> &mut CSTAR_WriteGlyphData_Response {
        self.write_glyph_data.mut_or_insert_default()
    }

    // Take field
    pub fn take_write_glyph_data(&mut self) -> CSTAR_WriteGlyphData_Response {
        self.write_glyph_data.take().unwrap_or_else(|| CSTAR_WriteGlyphData_Response::new())
    }

    fn generated_message_descriptor_data() -> crate::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(2);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(crate::reflect::rt::v2::make_message_field_accessor::<_, CSTAR_ReadGlyphData_Response>(
            "read_glyph_data",
            |m: &CSTAR_Response| { &m.read_glyph_data },
            |m: &mut CSTAR_Response| { &mut m.read_glyph_data },
        ));
        fields.push(crate::reflect::rt::v2::make_message_field_accessor::<_, CSTAR_WriteGlyphData_Response>(
            "write_glyph_data",
            |m: &CSTAR_Response| { &m.write_glyph_data },
            |m: &mut CSTAR_Response| { &mut m.write_glyph_data },
        ));
        crate::reflect::GeneratedMessageDescriptorData::new_2::<CSTAR_Response>(
            "CSTAR_Response",
            fields,
            oneofs,
        )
    }
}

impl crate::Message for CSTAR_Response {
    const NAME: &'static str = "CSTAR_Response";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut crate::CodedInputStream<'_>) -> crate::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    crate::rt::read_singular_message_into_field(is, &mut self.read_glyph_data)?;
                },
                18 => {
                    crate::rt::read_singular_message_into_field(is, &mut self.write_glyph_data)?;
                },
                tag => {
                    crate::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let Some(v) = self.read_glyph_data.as_ref() {
            let len = v.compute_size();
            my_size += 1 + crate::rt::compute_raw_varint64_size(len) + len;
        }
        if let Some(v) = self.write_glyph_data.as_ref() {
            let len = v.compute_size();
            my_size += 1 + crate::rt::compute_raw_varint64_size(len) + len;
        }
        my_size += crate::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut crate::CodedOutputStream<'_>) -> crate::Result<()> {
        if let Some(v) = self.read_glyph_data.as_ref() {
            crate::rt::write_message_field_with_cached_size(1, v, os)?;
        }
        if let Some(v) = self.write_glyph_data.as_ref() {
            crate::rt::write_message_field_with_cached_size(2, v, os)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &crate::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut crate::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> CSTAR_Response {
        CSTAR_Response::new()
    }

    fn clear(&mut self) {
        self.read_glyph_data.clear();
        self.write_glyph_data.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static CSTAR_Response {
        static instance: CSTAR_Response = CSTAR_Response {
            read_glyph_data: crate::MessageField::none(),
            write_glyph_data: crate::MessageField::none(),
            special_fields: crate::SpecialFields::new(),
        };
        &instance
    }
}

impl crate::MessageFull for CSTAR_Response {
    fn descriptor() -> crate::reflect::MessageDescriptor {
        static descriptor: crate::rt::Lazy<crate::reflect::MessageDescriptor> = crate::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("CSTAR_Response").unwrap()).clone()
    }
}

impl ::std::fmt::Display for CSTAR_Response {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        crate::text_format::fmt(self, f)
    }
}

impl crate::reflect::ProtobufValue for CSTAR_Response {
    type RuntimeType = crate::reflect::rt::RuntimeTypeMessage<Self>;
}

#[derive(Clone,Copy,PartialEq,Eq,Debug,Hash)]
// @@protoc_insertion_point(enum:E_STAR_GlyphWriteResult)
pub enum E_STAR_GlyphWriteResult {
    // @@protoc_insertion_point(enum_value:E_STAR_GlyphWriteResult.k_E_STAR_GlyphWriteResult_Success)
    k_E_STAR_GlyphWriteResult_Success = 0,
    // @@protoc_insertion_point(enum_value:E_STAR_GlyphWriteResult.k_E_STAR_GlyphWriteResult_InvalidMessage)
    k_E_STAR_GlyphWriteResult_InvalidMessage = 1,
    // @@protoc_insertion_point(enum_value:E_STAR_GlyphWriteResult.k_E_STAR_GlyphWriteResult_InvalidJSON)
    k_E_STAR_GlyphWriteResult_InvalidJSON = 2,
    // @@protoc_insertion_point(enum_value:E_STAR_GlyphWriteResult.k_E_STAR_GlyphWriteResult_SQLError)
    k_E_STAR_GlyphWriteResult_SQLError = 3,
}

impl crate::Enum for E_STAR_GlyphWriteResult {
    const NAME: &'static str = "E_STAR_GlyphWriteResult";

    fn value(&self) -> i32 {
        *self as i32
    }

    fn from_i32(value: i32) -> ::std::option::Option<E_STAR_GlyphWriteResult> {
        match value {
            0 => ::std::option::Option::Some(E_STAR_GlyphWriteResult::k_E_STAR_GlyphWriteResult_Success),
            1 => ::std::option::Option::Some(E_STAR_GlyphWriteResult::k_E_STAR_GlyphWriteResult_InvalidMessage),
            2 => ::std::option::Option::Some(E_STAR_GlyphWriteResult::k_E_STAR_GlyphWriteResult_InvalidJSON),
            3 => ::std::option::Option::Some(E_STAR_GlyphWriteResult::k_E_STAR_GlyphWriteResult_SQLError),
            _ => ::std::option::Option::None
        }
    }

    fn from_str(str: &str) -> ::std::option::Option<E_STAR_GlyphWriteResult> {
        match str {
            "k_E_STAR_GlyphWriteResult_Success" => ::std::option::Option::Some(E_STAR_GlyphWriteResult::k_E_STAR_GlyphWriteResult_Success),
            "k_E_STAR_GlyphWriteResult_InvalidMessage" => ::std::option::Option::Some(E_STAR_GlyphWriteResult::k_E_STAR_GlyphWriteResult_InvalidMessage),
            "k_E_STAR_GlyphWriteResult_InvalidJSON" => ::std::option::Option::Some(E_STAR_GlyphWriteResult::k_E_STAR_GlyphWriteResult_InvalidJSON),
            "k_E_STAR_GlyphWriteResult_SQLError" => ::std::option::Option::Some(E_STAR_GlyphWriteResult::k_E_STAR_GlyphWriteResult_SQLError),
            _ => ::std::option::Option::None
        }
    }

    const VALUES: &'static [E_STAR_GlyphWriteResult] = &[
        E_STAR_GlyphWriteResult::k_E_STAR_GlyphWriteResult_Success,
        E_STAR_GlyphWriteResult::k_E_STAR_GlyphWriteResult_InvalidMessage,
        E_STAR_GlyphWriteResult::k_E_STAR_GlyphWriteResult_InvalidJSON,
        E_STAR_GlyphWriteResult::k_E_STAR_GlyphWriteResult_SQLError,
    ];
}

impl crate::EnumFull for E_STAR_GlyphWriteResult {
    fn enum_descriptor() -> crate::reflect::EnumDescriptor {
        static descriptor: crate::rt::Lazy<crate::reflect::EnumDescriptor> = crate::rt::Lazy::new();
        descriptor.get(|| file_descriptor().enum_by_package_relative_name("E_STAR_GlyphWriteResult").unwrap()).clone()
    }

    fn descriptor(&self) -> crate::reflect::EnumValueDescriptor {
        let index = *self as usize;
        Self::enum_descriptor().value_by_index(index)
    }
}

impl ::std::default::Default for E_STAR_GlyphWriteResult {
    fn default() -> Self {
        E_STAR_GlyphWriteResult::k_E_STAR_GlyphWriteResult_Success
    }
}

impl E_STAR_GlyphWriteResult {
    fn generated_enum_descriptor_data() -> crate::reflect::GeneratedEnumDescriptorData {
        crate::reflect::GeneratedEnumDescriptorData::new::<E_STAR_GlyphWriteResult>("E_STAR_GlyphWriteResult")
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n$steammessages_star.steamclient.proto\x1a\x18steammessages_base.proto\
    \x1a,steammessages_unified_base.steamclient.proto\"=\n\x13CSTAR_KeyValue\
    Query\x12\x10\n\x03key\x18\x01\x20\x01(\tR\x03key\x12\x14\n\x05value\x18\
    \x02\x20\x01(\tR\x05value\"e\n\x16CSTAR_GlyphQueryParams\x12\x1b\n\tbund\
    le_id\x18\x01\x20\x01(\x04R\x08bundleId\x12.\n\x07queries\x18\x02\x20\
    \x03(\x0b2\x14.CSTAR_KeyValueQueryR\x07queries\"\x9d\x01\n\x1bCSTAR_Read\
    GlyphData_Request\x12:\n\x0cquery_params\x18\x01\x20\x01(\x0b2\x17.CSTAR\
    _GlyphQueryParamsR\x0bqueryParams\x12B\n\x1elast_modified_time_lower_lim\
    it\x18\x02\x20\x01(\tR\x1alastModifiedTimeLowerLimit\"\x88\x01\n\x0fCSTA\
    R_GlyphData\x12\x1d\n\nglyph_guid\x18\x01\x20\x01(\x0cR\tglyphGuid\x12.\
    \n\x13glyph_last_modified\x18\x02\x20\x01(\tR\x11glyphLastModified\x12&\
    \n\x0fglyph_json_data\x18\x03\x20\x01(\tR\rglyphJsonData\"l\n\x1cCSTAR_W\
    riteGlyphData_Request\x12\x1b\n\tbundle_id\x18\x01\x20\x01(\x04R\x08bund\
    leId\x12/\n\nglyph_data\x18\x02\x20\x03(\x0b2\x10.CSTAR_GlyphDataR\tglyp\
    hData\"\x9e\x01\n\rCSTAR_Request\x12D\n\x0fread_glyph_data\x18\x01\x20\
    \x01(\x0b2\x1c.CSTAR_ReadGlyphData_RequestR\rreadGlyphData\x12G\n\x10wri\
    te_glyph_data\x18\x02\x20\x01(\x0b2\x1d.CSTAR_WriteGlyphData_RequestR\
    \x0ewriteGlyphData\"l\n\x1cCSTAR_ReadGlyphData_Response\x12\x1b\n\tbundl\
    e_id\x18\x01\x20\x01(\x04R\x08bundleId\x12/\n\nglyph_data\x18\x02\x20\
    \x03(\x0b2\x10.CSTAR_GlyphDataR\tglyphData\"Q\n\x1dCSTAR_WriteGlyphData_\
    Response\x120\n\x06result\x18\x01\x20\x03(\x0e2\x18.E_STAR_GlyphWriteRes\
    ultR\x06result\"\xa1\x01\n\x0eCSTAR_Response\x12E\n\x0fread_glyph_data\
    \x18\x01\x20\x01(\x0b2\x1d.CSTAR_ReadGlyphData_ResponseR\rreadGlyphData\
    \x12H\n\x10write_glyph_data\x18\x02\x20\x01(\x0b2\x1e.CSTAR_WriteGlyphDa\
    ta_ResponseR\x0ewriteGlyphData*\xc1\x01\n\x17E_STAR_GlyphWriteResult\x12\
    %\n!k_E_STAR_GlyphWriteResult_Success\x10\0\x12,\n(k_E_STAR_GlyphWriteRe\
    sult_InvalidMessage\x10\x01\x12)\n%k_E_STAR_GlyphWriteResult_InvalidJSON\
    \x10\x02\x12&\n\"k_E_STAR_GlyphWriteResult_SQLError\x10\x0329\n\x04STAR\
    \x121\n\x0eProcessMessage\x12\x0e.CSTAR_Request\x1a\x0f.CSTAR_ResponseB\
    \x03\x80\x01\x01\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static crate::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: crate::rt::Lazy<crate::descriptor::FileDescriptorProto> = crate::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        crate::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static crate::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: crate::rt::Lazy<crate::reflect::GeneratedFileDescriptor> = crate::rt::Lazy::new();
    static file_descriptor: crate::rt::Lazy<crate::reflect::FileDescriptor> = crate::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(2);
            deps.push(super::steammessages_base::file_descriptor().clone());
            deps.push(super::steammessages_unified_base_steamclient::file_descriptor().clone());
            let mut messages = ::std::vec::Vec::with_capacity(9);
            messages.push(CSTAR_KeyValueQuery::generated_message_descriptor_data());
            messages.push(CSTAR_GlyphQueryParams::generated_message_descriptor_data());
            messages.push(CSTAR_ReadGlyphData_Request::generated_message_descriptor_data());
            messages.push(CSTAR_GlyphData::generated_message_descriptor_data());
            messages.push(CSTAR_WriteGlyphData_Request::generated_message_descriptor_data());
            messages.push(CSTAR_Request::generated_message_descriptor_data());
            messages.push(CSTAR_ReadGlyphData_Response::generated_message_descriptor_data());
            messages.push(CSTAR_WriteGlyphData_Response::generated_message_descriptor_data());
            messages.push(CSTAR_Response::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(1);
            enums.push(E_STAR_GlyphWriteResult::generated_enum_descriptor_data());
            crate::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        crate::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
