* TODO

- Steam Auth needs to be modified, to allow custom requests whilst maintaining store cookies. This would be used to
create trade offers. To check the trade offer history, we only need the api key.

** Trade related
- Create a trade offer from the user logged in, to a determined STEAMID, requesting one or multiple asset ids, and
offering nothing or something. (trade can't be completely empty, at least one item needs to be requested or sent);
- Check for transition of trade offers status (?);

*** Notes

- The sessionid cookie needs to be injected automatically, after we check for a successfull session. It should not be
 manually put inside the appropriate request;
- Trades sent but not yet confirmed, do not show at the trade history API endpoint.

- TradeHistory can be used to get the new assetids of traded items.

- Accept endpoint response is the trade id, example: {"tradeid":"3151905948734426645"}
- Decline endpoint response is the tradeofferid, example: {"tradeofferid":"4127436568"}. Request is only sessionid.
- Completed trades (accepted, for example) have their "trade id" on the GetTradeOffers endpoint. We can use this, to
check the new asset ids at the GetTradeHistory endpoint, by searching for "trade id" parameter.
